// src/components/ShortcutsModal.jsx
import React, { useEffect } from 'react';
import { X, Keyboard } from 'lucide-react';

export function ShortcutsModal({ isOpen, onClose, isParchment }) {
  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const shortcuts = [
    { key: 'Space', desc: '播放 / 暂停音频' },
    { key: '← / →', desc: '跳转至 上一句 / 下一句' },
    { key: 'R', desc: '从头重播当前句子' },
    { key: 'L', desc: '切换 单句精听循环' },
    { key: 'M', desc: '切换 盲听遮罩 / 听写模式' },
    { key: '↑ / ↓', desc: '调节音量大小' },
  ];

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn"
      onClick={onClose}
    >
      <div 
        onClick={(e) => e.stopPropagation()}
        className={`relative w-full max-w-md rounded-2xl border shadow-2xl p-6 transition-all duration-300 ${
          isParchment 
            ? 'bg-[#fbf6ea] border-[#dec9a5] text-[#2c221e]' 
            : 'bg-[#141b26] border-[#2b3a4f] text-[#e2d9c8]'
        }`}
      >
        <div className={`flex items-center justify-between mb-4 pb-2 border-b ${
          isParchment ? 'border-[#dec9a5]' : 'border-gray-700/40'
        }`}>
          <div className="flex items-center space-x-2">
            <Keyboard className="text-[#cba358]" size={20} />
            <h3 className="font-magical font-bold text-lg text-[#cba358]">
              精听快捷键指南
            </h3>
          </div>
          <button 
            onClick={onClose} 
            className="p-1 rounded-lg text-gray-400 hover:text-gray-200 transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        <div className="space-y-2.5 my-3">
          {shortcuts.map((sc, i) => (
            <div 
              key={i} 
              className={`flex items-center justify-between p-2.5 rounded-xl border text-xs sm:text-sm ${
                isParchment 
                  ? 'bg-[#f3ead7] border-[#dec9a5]' 
                  : 'bg-black/10 border-gray-700/30'
              }`}
            >
              <span className={isParchment ? 'text-[#3c2a1e] font-semibold' : 'text-gray-300'}>
                {sc.desc}
              </span>
              <kbd className="px-2 py-1 rounded bg-[#cba358]/20 border border-[#cba358]/40 text-[#cba358] font-mono font-bold text-xs">
                {sc.key}
              </kbd>
            </div>
          ))}
        </div>

        <p className={`text-xs text-center mt-4 ${isParchment ? 'text-[#6b543e]' : 'text-[#8c9ba5]'}`}>
          随时使用空格键与方向键，无需鼠标移动即可行云流水地练习精听！
        </p>
      </div>
    </div>
  );
}

// src/components/ShortcutsModal.vue
<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition-opacity duration-200 ease-out"
      enter-from-class="opacity-0"
      enter-to-class="opacity-100"
      leave-active-class="transition-opacity duration-150 ease-in"
      leave-from-class="opacity-100"
      leave-to-class="opacity-0"
    >
      <div
        v-if="isOpen"
        class="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4"
        @click="$emit('close')"
        role="dialog"
        aria-modal="true"
        aria-label="操作快捷键与手势指南"
      >
        <div
          class="bg-[#fbf9f5] border border-[#e8ddd0] rounded-2xl max-w-md w-full max-h-[85vh] flex flex-col shadow-2xl overflow-hidden"
          @click.stop
        >
          <!-- Header -->
          <div class="px-5 py-4 border-b border-[#e8ddd0] flex items-center justify-between shrink-0">
            <div class="flex items-center gap-2">
              <div class="w-8 h-8 rounded-lg bg-[#d97706]/15 border border-[#d97706]/30 flex items-center justify-center text-[#d97706]">
                <Keyboard class="w-4 h-4" />
              </div>
              <h2 class="font-serif text-base font-semibold text-[#1e1610]">
                快捷键与手势指南
              </h2>
            </div>

            <button
              type="button"
              @click="$emit('close')"
              class="min-h-[44px] min-w-[44px] p-2 rounded-lg text-[#78695d] hover:text-[#1e1610] hover:bg-[#f4ebe1] flex items-center justify-center transition-colors"
              aria-label="关闭快捷键指南"
            >
              <X class="w-5 h-5" />
            </button>
          </div>

          <!-- Shortcuts List -->
          <div class="flex-1 overflow-y-auto p-5 space-y-3">
            <div
              v-for="item in shortcuts"
              :key="item.key"
              class="p-3 bg-white/70 border border-[#e8ddd0] rounded-xl flex items-center justify-between gap-3"
            >
              <span class="text-xs text-[#4a3b32] font-medium">
                {{ item.desc }}
              </span>
              <kbd class="px-2.5 py-1 text-xs font-mono font-semibold bg-[#f4ebe1] border border-[#e8ddd0] text-[#1e1610] rounded-lg shadow-inner">
                {{ item.key }}
              </kbd>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup>
import { Keyboard, X } from 'lucide-vue-next'

defineProps({
  isOpen: {
    type: Boolean,
    default: false
  }
})

defineEmits(['close'])

const shortcuts = [
  { key: 'Space', desc: '播放 / 暂停音频' },
  { key: '← (Left)', desc: '快退 5 秒' },
  { key: '→ (Right)', desc: '快进 5 秒' },
  { key: '轻点字幕', desc: '跳转至对应句子起播' },
  { key: '盲听模式', desc: '开启迷雾遮罩强制听音辨意' }
]
</script>
