// src/components/VocabularyDrawer.jsx
import React, { useState, useEffect } from 'react';
import { 
  X, 
  Trash2, 
  Volume2, 
  Download, 
  Sparkles, 
  Search, 
  CheckCircle,
  BookOpen,
  BrainCircuit,
  Bookmark
} from 'lucide-react';

import { generateAnkiTSV, downloadAnkiFile } from '../utils/ankiExport';

export function VocabularyDrawer({
  isOpen,
  onClose,
  vocabList,
  onRemoveWord,
  onClearAll,
  isParchment,
  onOpenSrs
}) {
  const [searchTerm, setSearchTerm] = useState('');
  const [toastMessage, setToastMessage] = useState(null);

  const showToast = (msg) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 2500);
  };

  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const filteredList = vocabList.filter(item => 
    item.word.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (item.translation && item.translation.includes(searchTerm))
  );

  const playPronunciation = (word) => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(word);
      utterance.lang = 'en-GB';
      utterance.rate = 0.9;
      window.speechSynthesis.speak(utterance);
    }
  };

  const handleExportAnki = () => {
    if (!vocabList || vocabList.length === 0) return;
    const content = generateAnkiTSV(vocabList, { deckName: 'Hogwarts Magic English' });
    downloadAnkiFile(content, `hogwarts_anki_${Date.now()}.tsv`);
    showToast('已导出 Anki 牌组文件 (.tsv)，可在 Anki 中直接导入！');
  };

  const handleExportAnkiCloze = () => {
    if (!vocabList || vocabList.length === 0) return;
    const content = generateAnkiTSV(vocabList, { deckName: 'Hogwarts Magic English (Cloze)', cloze: true });
    downloadAnkiFile(content, `hogwarts_anki_cloze_${Date.now()}.tsv`);
    showToast('已导出 Anki Cloze 填空卡牌组 (.tsv)！');
  };

  const handleExportCSV = () => {
    if (vocabList.length === 0) return;
    const header = 'Word,Phonetic,Part of Speech,Translation,Context\n';
    const rows = vocabList.map(v => 
      `"${v.word}","${v.phonetic || ''}","${v.pos || ''}","${(v.translation || '').replace(/"/g, '""')}","${(v.context || '').replace(/"/g, '""')}"`
    ).join('\n');

    const blob = new Blob(['\uFEFF' + header + rows], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `hogwarts_vocab_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    showToast('已成功导出 CSV 单词表格！');
  };

  const todayStr = new Date().toISOString().split('T')[0];

  const renderSrsBadge = (item) => {
    const level = item.srsLevel || item.srsBox || 1;
    const isDue = !item.nextReviewDate || item.nextReviewDate <= todayStr;

    const levelConfigs = {
      1: { label: 'Box 1 · 初学', color: 'bg-amber-100/90 text-amber-900 border-amber-300' },
      2: { label: 'Box 2 · 巩固', color: 'bg-amber-200/70 text-amber-950 border-amber-400' },
      3: { label: 'Box 3 · 熟记', color: 'bg-blue-100/90 text-blue-900 border-blue-300' },
      4: { label: 'Box 4 · 长效', color: 'bg-purple-100/90 text-purple-900 border-purple-300' },
      5: { label: 'Box 5 · 永久掌握', color: 'bg-emerald-100 text-emerald-900 border-emerald-400 font-bold' }
    };
    const config = levelConfigs[level] || levelConfigs[1];

    return (
      <div className="flex items-center gap-1.5 mt-1 flex-wrap">
        <span className={`text-[10px] px-2 py-0.5 rounded-md border font-semibold ${config.color}`}>
          {config.label}
        </span>
        {isDue && (
          <span className="text-[10px] px-1.5 py-0.5 rounded-md bg-gradient-to-r from-amber-500 to-amber-600 text-white font-bold animate-pulse border border-amber-600" title="记忆封印松动，需要艾宾浩斯重铸">
            待重炼 · 封印松动
          </span>
        )}
      </div>
    );
  };

  return (
    <div 
      className="fixed inset-0 z-50 overflow-hidden bg-black/60 backdrop-blur-sm flex items-end sm:items-stretch sm:justify-end animate-fadeIn"
      onClick={onClose}
    >
      <div 
        onClick={(e) => e.stopPropagation()}
        className="w-full sm:w-screen sm:max-w-md flex flex-col max-h-[92dvh] sm:max-h-full rounded-t-3xl sm:rounded-none border-t sm:border-t-0 sm:border-l border-[#e8ddd0] bg-[#fbf9f5] text-[#1e1610] transition-colors duration-300 pb-safe overflow-hidden"
      >
        {/* Mobile Pull Handle Indicator */}
        <div className="sm:hidden w-10 h-1.5 bg-stone-300 rounded-full mx-auto my-2.5 shrink-0" />

        {/* Drawer Header */}
        <div className="px-4 sm:px-5 py-3.5 sm:py-4 border-b border-[#e8ddd0] bg-white flex items-center justify-between gap-2 shrink-0">
            <div className="flex items-center space-x-2 min-w-0 flex-1">
              <BookOpen className="w-5 h-5 text-amber-600 shrink-0" />
              <div className="min-w-0 flex-1">
                <h2 className="font-bold text-base sm:text-lg text-amber-950 truncate whitespace-nowrap">
                  <span className="font-magical">魔法生词本 ({vocabList.length})</span>
                </h2>
                <p className="text-[11px] sm:text-xs text-stone-500 truncate">精听原著词汇与例句笔记</p>
              </div>
            </div>

              {onOpenSrs && vocabList.length > 0 && (
                <button
                  onClick={() => {
                    onClose();
                    onOpenSrs();
                  }}
                  className="duo-btn-primary min-h-[44px] px-3 sm:px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-1.5 cursor-pointer shrink-0 whitespace-nowrap"
                  title="启动艾宾浩斯智能翻转闪卡 (SRS 遗忘曲线算法)"
                >
                  <BrainCircuit size={15} className="shrink-0" />
                  <span>艾宾浩斯背词</span>
                </button>
              )}

              <button
                onClick={onClose}
                className="duo-touch-target rounded-xl border border-[#e8ddd0] bg-white hover:bg-stone-100 text-stone-600 hover:text-amber-950 hover:border-amber-300 transition-all active:scale-90 cursor-pointer shrink-0"
                title="关闭生词本"
              >
                <X size={18} />
              </button>
            </div>

          {/* Search input - only show when vocabList has items */}
          {vocabList.length > 0 && (
                <div className="p-3 border-b border-[#e8ddd0] bg-white">
                  <div className="relative">
                    <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-400" />
                    <input
                      type="search"
                      enterKeyHint="search"
                      autoCapitalize="none"
                      autoCorrect="off"
                      spellCheck="false"
                      placeholder="搜索生词或中文释义..."
                      value={searchTerm}
                      onChange={(e) => setSearchTerm(e.target.value)}
                      className="w-full pl-9 pr-3 py-2 text-base sm:text-xs rounded-xl border border-[#e8ddd0] bg-stone-50 text-[#1e1610] focus:outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-400/20 transition-all"
                    />
                  </div>
                </div>
              )}

              {/* Vocab Cards List */}
              <div className="flex-1 overflow-y-auto p-4 space-y-3 ios-scroll">
                {vocabList.length === 0 ? (
                  <div className="flex-1 flex flex-col items-center justify-center py-16 px-4 text-center my-auto">
                    <div className="w-16 h-16 rounded-3xl bg-amber-500/10 border border-amber-300/80 flex items-center justify-center text-amber-600 mb-4 animate-pulse">
                      <Bookmark size={28} className="text-amber-600" />
                    </div>
                    <h3 className="font-magical font-bold text-base text-amber-950 mb-1">
                      暂无生词 · 魔杖尚未收录新词
                    </h3>
                    <p className="text-xs text-stone-500 max-w-xs leading-relaxed mb-6">
                      在精听研读原著时，轻点任意英文单词即可实时查看权威释义，并一键收录至专属魔法生词本！
                    </p>
                    <button
                      onClick={onClose}
                      className="duo-btn-primary min-h-[44px] px-6 py-2 rounded-2xl text-xs font-bold flex items-center gap-2 cursor-pointer active:scale-95"
                    >
                      <Sparkles size={15} />
                      <span>去精听挑词入库</span>
                    </button>
                  </div>
                ) : filteredList.length === 0 ? (
                  <div className="text-center py-16 text-stone-400 text-xs">
                    <p className="font-bold text-sm text-stone-700 mb-1">未找到匹配生词</p>
                    <p className="text-xs mb-3">没有搜索到包含 “{searchTerm}” 的生词或释义</p>
                    <button
                      onClick={() => setSearchTerm('')}
                      className="duo-btn-secondary px-3 py-1.5 rounded-xl text-xs font-bold text-amber-900 cursor-pointer"
                    >
                      清除搜索条件
                    </button>
                  </div>
                ) : (
                  filteredList.map((item) => {
                    const isDue = !item.nextReviewDate || item.nextReviewDate <= todayStr;
                    return (
                      <div
                        key={item.id || item.word}
                        className={`p-3.5 rounded-2xl border transition-all ${
                          isDue
                            ? 'bg-amber-500/5 border-amber-400/90 ring-1 ring-amber-400/30'
                            : 'duo-card duo-card-hover'
                        }`}
                      >
                      <div className="flex items-start justify-between">
                        <div className="flex-1 min-w-0 pr-2">
                          <div className="flex items-center space-x-2 flex-wrap">
                            <h4 className="font-magical font-bold text-base text-amber-950">
                              {item.word}
                            </h4>
                            {item.phonetic && (
                              <span className="font-mono text-xs px-2 py-0.5 rounded bg-amber-500/10 text-amber-800 font-semibold">
                                {item.phonetic}
                              </span>
                            )}
                            {item.isHpLore ? (
                              <span className="text-[10px] px-2 py-0.5 rounded-full bg-red-100 text-red-900 border border-red-300/80 font-bold">
                                原著魔法
                              </span>
                            ) : item.tag === '中考核心' ? (
                              <span className="text-[10px] px-2 py-0.5 rounded-full bg-amber-100 text-amber-900 border border-amber-300/80 font-bold">
                                中考核心
                              </span>
                            ) : (
                              <span className="text-[10px] px-2 py-0.5 rounded-full bg-stone-100 text-stone-700 border border-stone-300 font-bold">
                                进阶拓展
                              </span>
                            )}
                            {/* SRS status dot */}
                            {item.srsBox !== undefined && (
                              <span className={`inline-block w-2 h-2 rounded-full ml-1.5 align-middle ${
                                item.srsBox >= 5 ? 'bg-emerald-500' :
                                item.srsBox >= 4 ? 'bg-amber-400' :
                                item.srsBox >= 2 ? 'bg-orange-400' : 'bg-red-400'
                              }`} title={`SRS盒子 ${item.srsBox || 1}: ${item.srsBox >= 5 ? '已掌握' : '复习中'}`} />
                            )}
                          </div>
                          {renderSrsBadge(item)}
                        </div>

                        <div className="flex items-center space-x-1 shrink-0">
                          <button
                            onClick={() => playPronunciation(item.word)}
                            className="duo-touch-target rounded-xl border border-transparent hover:border-amber-300/80 bg-transparent hover:bg-amber-50 text-stone-500 hover:text-amber-800 transition-all active:scale-90 cursor-pointer"
                            title="试听纯正英音发音"
                          >
                            <Volume2 size={16} />
                          </button>
                          <button
                            onClick={() => onRemoveWord(item.word)}
                            className="duo-touch-target rounded-xl border border-transparent hover:border-rose-300/80 bg-transparent hover:bg-rose-50 text-stone-400 hover:text-rose-600 transition-all active:scale-90 cursor-pointer"
                            title="从生词本移除"
                          >
                            <Trash2 size={16} />
                          </button>
                        </div>
                      </div>

                      <p className="text-xs sm:text-sm font-reading mt-1.5 font-bold text-amber-950">
                        {item.translation}
                      </p>

                      {item.context && (
                        <p className="text-[11px] font-reading italic mt-2 border-t border-[#e8ddd0] pt-1.5 line-clamp-2 text-stone-600">
                          "{item.context}"
                        </p>
                      )}
                    </div>
                  );
                })
              )}
              </div>

              {/* Bottom Actions */}
              <div className="p-3.5 sm:p-4 border-t border-[#e8ddd0] bg-white flex flex-wrap items-center justify-between gap-2 text-xs shrink-0">
                <div className="flex items-center gap-2">
                  <button
                    disabled={vocabList.length === 0}
                    onClick={handleExportAnki}
                    className={`duo-btn-secondary min-h-[40px] flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs whitespace-nowrap ${vocabList.length === 0 ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
                    title="导出为标准 Anki 卡片牌组 (.tsv)"
                  >
                    <Sparkles size={14} className="text-amber-600 shrink-0" />
                    <span>导出至 Anki (TSV)</span>
                  </button>

                  <button
                    disabled={vocabList.length === 0}
                    onClick={handleExportAnkiCloze}
                    className={`duo-btn-secondary min-h-[40px] flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs whitespace-nowrap ${vocabList.length === 0 ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
                    title="导出为 Anki 挖空填空卡 (Cloze Deletion)"
                  >
                    <BrainCircuit size={14} className="text-amber-700 shrink-0" />
                    <span>Anki 挖空卡</span>
                  </button>

                  <button
                    disabled={vocabList.length === 0}
                    onClick={handleExportCSV}
                    className={`duo-btn-secondary min-h-[40px] flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs whitespace-nowrap ${vocabList.length === 0 ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
                    title="导出为通用表格 CSV 格式"
                  >
                    <Download size={14} className="shrink-0" />
                    <span>导出 CSV</span>
                  </button>
                </div>

                <button
                  disabled={vocabList.length === 0}
                  onClick={onClearAll}
                  className={`min-h-[40px] px-3 py-1.5 rounded-xl text-xs font-bold border border-rose-200 text-rose-700 bg-rose-50/60 transition-all whitespace-nowrap flex items-center gap-1 ${vocabList.length === 0 ? 'opacity-50 cursor-not-allowed' : 'hover:bg-rose-100 hover:border-rose-300 active:scale-95 cursor-pointer'}`}
                  title="清空生词本内所有单词"
                >
                  <Trash2 size={13} className="text-rose-600 shrink-0" />
                  <span>清空生词本</span>
                </button>
              </div>

          {/* Toast Feedback Notification */}
          {toastMessage && (
            <div className="absolute bottom-20 left-4 right-4 z-50 animate-bounce">
              <div className="p-3 rounded-2xl bg-emerald-700/95 border border-emerald-500 text-white text-xs font-bold flex items-center justify-center gap-2">
                <CheckCircle size={15} />
                <span>{toastMessage}</span>
              </div>
            </div>
          )}
      </div>
    </div>
  );
}

// src/components/VocabularyDrawer.vue
<template>
  <Teleport to="body">
    <!-- Backdrop -->
    <Transition
      enter-active-class="transition-opacity duration-300 ease-out"
      enter-from-class="opacity-0"
      enter-to-class="opacity-100"
      leave-active-class="transition-opacity duration-200 ease-in"
      leave-from-class="opacity-100"
      leave-to-class="opacity-0"
    >
      <div
        v-if="isOpen"
        class="fixed inset-0 z-40 bg-black/40 backdrop-blur-sm"
        @click="handleClose"
        aria-hidden="true"
      ></div>
    </Transition>

    <!-- Drawer Panel -->
    <Transition
      enter-active-class="transition-transform duration-300 ease-out"
      enter-from-class="translate-x-full"
      enter-to-class="translate-x-0"
      leave-active-class="transition-transform duration-200 ease-in"
      leave-from-class="translate-x-0"
      leave-to-class="translate-x-full"
    >
      <aside
        v-if="isOpen"
        class="fixed top-0 right-0 bottom-0 z-50 w-full max-w-lg bg-[#f8f8f6] border-l border-[#e4e4e7] flex flex-col"
        :style="sheetStyle"
        role="dialog"
        aria-modal="true"
        aria-label="艾宾浩斯生词本"
      >
        <!-- Pull Handle (Mobile only) -->
        <div
          class="min-h-[44px] flex items-center justify-center sm:hidden cursor-grab active:cursor-grabbing touch-none shrink-0 border-b border-[#e4e4e7] bg-white"
          @touchstart="onTouchStart"
          @touchmove="handleDragTouchMove"
          @touchend="onTouchEnd"
        >
          <div class="w-10 h-1.5 rounded-full bg-[#d4d4d8]"></div>
        </div>

        <!-- Header -->
        <div class="p-4 border-b border-[#e4e4e7] bg-white flex items-center justify-between shrink-0">
          <div class="flex items-center gap-2">
            <BookMarked class="w-5 h-5 text-[#2563eb]" />
            <h2 class="font-serif text-base font-semibold text-[#18181b]">
              艾宾浩斯生词本 ({{ vocabStore.vocabList.length }})
            </h2>
          </div>

          <button
            type="button"
            @click="handleClose"
            class="min-h-[44px] min-w-[44px] p-2 rounded-lg text-[#71717a] hover:text-[#18181b] hover:bg-[#f4f4f5] flex items-center justify-center transition-colors cursor-pointer"
            aria-label="关闭生词本"
          >
            <X class="w-5 h-5" />
          </button>
        </div>

        <!-- Search Input Bar -->
        <div class="p-3 border-b border-[#e4e4e7] bg-white shrink-0">
          <div class="relative flex items-center">
            <Search class="absolute left-3 w-4 h-4 text-[#71717a] pointer-events-none" />
            <input
              v-model="searchQuery"
              type="text"
              placeholder="搜索生词或中文释义..."
              class="w-full h-11 pl-9 pr-9 bg-[#f8f8f6] border border-[#e4e4e7] rounded-xl text-base sm:text-sm text-[#18181b] placeholder-[#a1a1aa] focus:outline-none focus:border-[#2563eb] focus:bg-white transition-colors"
              aria-label="搜索生词本单词"
            />
            <button
              v-if="searchQuery"
              type="button"
              @click="searchQuery = ''"
              class="absolute right-1.5 min-h-[44px] min-w-[44px] p-2 text-[#a1a1aa] hover:text-[#18181b] flex items-center justify-center rounded-lg transition-colors cursor-pointer"
              aria-label="清空搜索内容"
            >
              <X class="w-4 h-4" />
            </button>
          </div>
        </div>

        <!-- 3-Tier Action Pyramid Toolbar -->
        <div class="p-4 border-b border-[#e4e4e7] bg-white space-y-2 shrink-0">
          <!-- Primary CTA: Print A4 Cut-out Flashcards PDF -->
          <button
            type="button"
            @click="handlePrintCards"
            class="min-h-[44px] w-full py-2.5 px-4 bg-[#18181b] hover:bg-[#27272a] text-white text-xs font-semibold rounded-xl flex items-center justify-center gap-2 shadow-sm transition-all active:scale-95 cursor-pointer"
          >
            <Printer class="w-4 h-4" />
            <span>打印羊皮纸单词卡 (PDF)</span>
          </button>

          <!-- Secondary Actions -->
          <div class="flex items-center gap-2">
            <button
              type="button"
              @click="handleExportAnki"
              class="min-h-[44px] flex-1 py-2 px-3 bg-[#f4f4f5] hover:bg-[#e4e4e7] border border-[#e4e4e7] text-[#18181b] text-xs font-medium rounded-xl flex items-center justify-center gap-1.5 transition-colors active:scale-95 cursor-pointer"
            >
              <Download class="w-4 h-4 text-[#2563eb]" />
              <span>导出 Anki (TSV)</span>
            </button>

            <button
              type="button"
              @click="handleClearVocab"
              class="min-h-[44px] px-3 py-2 text-[#b91c1c] hover:bg-rose-50 border border-transparent hover:border-rose-200 text-xs font-medium rounded-xl flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              <Trash2 class="w-4 h-4" />
              <span>清空</span>
            </button>
          </div>
        </div>

        <!-- Leitner 5-Box Distribution Tabs -->
        <div class="p-3 border-b border-[#e4e4e7] bg-white/70 flex gap-1.5 overflow-x-auto no-scrollbar shrink-0">
          <button
            type="button"
            @click="activeBox = null"
            :class="[
              'min-h-[44px] px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-colors border cursor-pointer',
              activeBox === null
                ? 'bg-blue-50 border-[#2563eb] text-[#2563eb]'
                : 'border-transparent text-[#71717a] hover:bg-[#f4f4f5]'
            ]"
          >
            全部 ({{ vocabStore.vocabList.length }})
          </button>

          <button
            v-for="b in 5"
            :key="b"
            type="button"
            @click="activeBox = b"
            :class="[
              'min-h-[44px] px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-colors border cursor-pointer',
              activeBox === b
                ? 'bg-blue-50 border-[#2563eb] text-[#2563eb]'
                : 'border-transparent text-[#71717a] hover:bg-[#f4f4f5]'
            ]"
          >
            Box {{ b }} ({{ getBoxCount(b) }})
          </button>
        </div>

        <!-- Vocabulary Cards List -->
        <div
          ref="scrollContainerRef"
          class="flex-1 overflow-y-auto p-4 space-y-3"
          @touchstart="onTouchStart"
          @touchmove="handleContentTouchMove"
          @touchend="onTouchEnd"
        >
          <div
            v-if="filteredList.length === 0"
            class="text-center py-16 text-sm text-[#71717a]"
          >
            {{ searchQuery ? '未找到匹配的生词' : '当前分类暂无生词' }}
          </div>

          <div
            v-for="item in filteredList"
            :key="item.id || item.word"
            class="p-4 bg-white border border-[#e4e4e7] rounded-xl space-y-2 hover:border-blue-300 transition-colors"
          >
            <!-- Word Header -->
            <div class="flex items-start justify-between gap-2">
              <div class="flex items-center gap-2 flex-wrap min-w-0">
                <h3 class="font-serif text-base font-bold text-[#18181b] truncate">
                  {{ item.word }}
                </h3>
                <!-- Audio pronunciation button -->
                <button
                  type="button"
                  @click="playPronunciation(item.word)"
                  class="min-h-[44px] min-w-[44px] p-2 rounded-lg text-[#71717a] hover:text-[#18181b] hover:bg-[#f4f4f5] flex items-center justify-center transition-colors cursor-pointer active:scale-95"
                  :aria-label="'朗读发音 ' + item.word"
                  title="朗读发音"
                >
                  <Volume2 class="w-4 h-4" />
                </button>
                <span v-if="item.phonetic || item.ipa" class="text-xs font-mono text-[#a1a1aa]">
                  {{ item.phonetic || item.ipa }}
                </span>
              </div>

              <!-- Box Pill -->
              <span class="text-[10px] font-mono px-2 py-0.5 rounded-full bg-blue-50 border border-blue-200 text-[#2563eb] shrink-0">
                Box {{ item.box || 1 }}
              </span>
            </div>

            <!-- Meaning -->
            <p class="text-xs text-[#52525b] font-sans">
              {{ item.definition || item.meaning || '' }}
            </p>

            <!-- Context Quote -->
            <p v-if="item.contextQuote" class="text-xs text-[#71717a] font-serif italic border-l-2 border-[#e4e4e7] pl-2 mt-1">
              "{{ item.contextQuote }}"
            </p>

            <!-- Card Actions -->
            <div class="pt-2 flex items-center justify-between border-t border-[#f4f4f5]">
              <span class="text-[10px] text-[#a1a1aa] font-mono">
                {{ getBoxInterval(item.box || 1) }}
              </span>

              <div class="flex items-center gap-1">
                <button
                  type="button"
                  @click="promoteBox(item)"
                  class="min-h-[44px] px-2.5 py-1 text-[11px] font-medium text-emerald-700 hover:bg-emerald-50 rounded-lg transition-colors cursor-pointer"
                  title="提升至下一个记忆盒"
                >
                  熟记 +1
                </button>
                <button
                  type="button"
                  @click="deleteWord(item)"
                  class="min-h-[44px] px-2.5 py-1 text-[11px] font-medium text-rose-700 hover:bg-rose-50 rounded-lg transition-colors cursor-pointer"
                  title="删除生词"
                >
                  移除
                </button>
              </div>
            </div>
          </div>
        </div>
      </aside>
    </Transition>
  </Teleport>
</template>

<script setup>
import { ref, computed, onBeforeUnmount } from 'vue'
import { useVocabStore } from '../stores/vocabStore.js'
import { generateAnkiTSV, downloadAnkiFile } from '../utils/ankiExport.js'
import { generatePrintableParchmentHTML } from '../utils/parchmentPdfGenerator.js'
import { useBottomSheet } from '../composables/useBottomSheet.js'
import {
  BookMarked,
  Printer,
  Download,
  Trash2,
  X,
  Search,
  Volume2
} from 'lucide-vue-next'

defineProps({
  isOpen: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['close'])

const vocabStore = useVocabStore()
const activeBox = ref(null)
const searchQuery = ref('')
const scrollContainerRef = ref(null)

function handleClose() {
  if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
    try {
      window.speechSynthesis.cancel()
    } catch (_) {}
  }
  emit('close')
}

const {
  sheetStyle,
  onTouchStart,
  onTouchMove,
  onTouchEnd
} = useBottomSheet({
  threshold: 80,
  onClose: () => handleClose()
})

function handleDragTouchMove(e) {
  onTouchMove(e, 0)
}

function handleContentTouchMove(e) {
  const st = scrollContainerRef.value ? scrollContainerRef.value.scrollTop : 0
  onTouchMove(e, st)
}

function playPronunciation(word) {
  if (!word) return
  if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
    try {
      window.speechSynthesis.cancel()
      const utt = new SpeechSynthesisUtterance(word)
      utt.lang = 'en-GB'
      utt.rate = 0.85
      window.speechSynthesis.speak(utt)
    } catch (_) {}
  }
}

const filteredList = computed(() => {
  const q = searchQuery.value.trim().toLowerCase()
  return vocabStore.vocabList.filter((item) => {
    if (activeBox.value !== null && (item.box || 1) !== activeBox.value) {
      return false
    }
    if (!q) return true
    const matchesWord = item.word && item.word.toLowerCase().includes(searchQuery.value.toLowerCase())
    const matchesDef = (item.definition && item.definition.includes(searchQuery.value)) || (item.definition && item.definition.toLowerCase().includes(q)) || (item.meaning && item.meaning.toLowerCase().includes(q))
    return Boolean(matchesWord || matchesDef)
  })
})

function getBoxCount(boxNum) {
  return vocabStore.vocabList.filter((item) => (item.box || 1) === boxNum).length
}

function getBoxInterval(box) {
  const map = { 1: '1天复习', 2: '3天复习', 3: '7天复习', 4: '14天复习', 5: '30天复习' }
  return map[box] || '1天复习'
}

function promoteBox(item) {
  vocabStore.promoteBox(item)
}

function deleteWord(item) {
  vocabStore.deleteWord(item)
}

function handleClearVocab() {
  if (typeof window !== 'undefined' && window.confirm('确认清空生词本中的所有单词吗？此操作无法撤销。')) {
    vocabStore.clearAll()
  }
}

function handleExportAnki() {
  const tsv = generateAnkiTSV(vocabStore.vocabList, { deckName: 'Hogwarts Magic English' })
  downloadAnkiFile(tsv, 'hogwarts_anki_deck.tsv')
}

function handlePrintCards() {
  const html = generatePrintableParchmentHTML(vocabStore.vocabList, {
    title: '霍格沃茨魔法生词卡 (A4 可剪裁打印版)'
  })
  if (typeof window !== 'undefined') {
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(html)
      printWindow.document.close()
      printWindow.focus()
      setTimeout(() => {
        printWindow.print()
      }, 500)
    }
  }
}

onBeforeUnmount(() => {
  if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
    try {
      window.speechSynthesis.cancel()
    } catch (_) {}
  }
})
</script>
